apiVersion: v1
kind: Service
metadata:
  name: dvwa - service
spec:
  type: NodePort
  selector:
    app: dvwa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    type: LoadBalancer
    (base) [200t@GUI ~]#
